### ISSUE TITLE
Milestone

### ISSUE THREAD

**Issue by jasrajsb** [jasrajsb/bhm-iitd#37]
- [ ]  gallery in hostel pages
- [ ]  social icon links in data.json
- [ ]  student team structure component
- [ ]  mess menu UI change & merge
- [ ]  Resources - remove stuff related to acads
- [ ]  Hostel Hero Widget - add location and modal to complain form
- [ ]  Profile Card - Insta, Phone, Mail, LinkedIn
